baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Welcome to Magic Inn'

## Site Settings

logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

# Info

address = "Prague, Czech Republic"
email = "magicinn.dev@gmail.com"
phone = "+16692138392"

# Socials

twitter = "#"
facebook = "#"


# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = " "

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#signup"
  weight = 3


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04